// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX4a9EqXXjG51dUiodzT4PwSAfsEyOF2k',
    appId: '1:865964567283:web:94eb3f9bd28edc64c3e586',
    messagingSenderId: '865964567283',
    projectId: 'juclub',
    authDomain: 'juclub.firebaseapp.com',
    storageBucket: 'juclub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUWtCrmmTiOYzd3iS353nw15LWiiCIeI',
    appId: '1:865964567283:android:00c5082aa788eda1c3e586',
    messagingSenderId: '865964567283',
    projectId: 'juclub',
    storageBucket: 'juclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOyqYuGl2Vieqz8arqLNrVmrvUADrEFRA',
    appId: '1:865964567283:ios:eb0d297e76814b8dc3e586',
    messagingSenderId: '865964567283',
    projectId: 'juclub',
    storageBucket: 'juclub.appspot.com',
    iosClientId: '865964567283-sdeoin1g1e1d4kvpls94nqmja4903ief.apps.googleusercontent.com',
    iosBundleId: 'com.juclub.ios',
  );
}
